#!/bin/sh
set -e

echo "Initializing..."
echo "Current DB_CONNECTION Env Var: $DB_CONNECTION"

# Regenerate .env with forceful single quotes
echo "Generating .env file..."

# Write lines without using variables immediately to ensure content
echo "APP_NAME='ShivaShine'" > .env
echo "APP_ENV='production'" >> .env
echo "APP_DEBUG='flase'" >> .env
echo "LOG_CHANNEL='stderr'" >> .env

# Database - Critical Section
# Only default to pgsql if we have a host, otherwise stay flexible or default to mysql
if [ -z "$DB_CONNECTION" ]; then
    if [ -n "$DB_HOST" ]; then
        export DB_CONNECTION='pgsql'
    else
        export DB_CONNECTION='mysql'
    fi
fi

# Warn if pgsql is selected but no host is provided (will likely fail with 127.0.0.1)
if [ "$DB_CONNECTION" = "pgsql" ] && [ -z "$DB_HOST" ]; then
    echo "WARNING: DB_CONNECTION is set to pgsql but DB_HOST is missing. Connection may fail."
fi

# Ensure SQLite file exists just in case Laravel defaults to it
mkdir -p database
touch database/database.sqlite

# Clear any existing .env to start fresh with provided variables
echo "# Generated by docker-entrypoint.sh" > .env
echo "APP_NAME='ShivaShine'" >> .env
echo "APP_ENV='production'" >> .env
echo "APP_DEBUG='flase'" >> .env
echo "LOG_CHANNEL='stderr'" >> .env

# Write database configuration
echo "DB_CONNECTION=$DB_CONNECTION" >> .env
[ -n "$DB_HOST" ] && echo "DB_HOST=$DB_HOST" >> .env
[ -n "$DB_PORT" ] && echo "DB_PORT=$DB_PORT" >> .env
[ -n "$DB_DATABASE" ] && echo "DB_DATABASE=$DB_DATABASE" >> .env
[ -n "$DB_USERNAME" ] && echo "DB_USERNAME=$DB_USERNAME" >> .env
[ -n "$DB_PASSWORD" ] && echo "DB_PASSWORD=$DB_PASSWORD" >> .env

[ -n "$APP_KEY" ] && echo "APP_KEY=$APP_KEY" >> .env
[ -n "$APP_URL" ] && echo "APP_URL=$APP_URL" >> .env

echo "Done generating .env"

# CLEAR ALL CACHES - Use force
php artisan config:clear
php artisan cache:clear

# Debug: Print the connection config before running migrate
echo "Checking Laravel Database Config..."
php -r "echo 'Configured DB Connection: ' . config('database.default') . PHP_EOL;"

# Run migrations
echo "Running migrations..."
php artisan migrate --force

echo "Starting server..."
exec php artisan serve --host=0.0.0.0 --port=10000
