#!/bin/sh
set -e

echo "Initializing..."
echo "Current DB_CONNECTION Env Var: $DB_CONNECTION"

# Ensure SQLite file exists just in case Laravel defaults to it
mkdir -p database
touch database/database.sqlite

# Clear any existing .env to start fresh with provided variables
echo "# Generated by docker-entrypoint.sh" > .env
echo "APP_NAME=${APP_NAME:-ShivaShine}" >> .env
echo "APP_ENV=${APP_ENV:-production}" >> .env
echo "APP_DEBUG=${APP_DEBUG:-false}" >> .env
echo "LOG_CHANNEL=${LOG_CHANNEL:-stderr}" >> .env

# Generate APP_KEY if not provided
if [ -z "$APP_KEY" ]; then
    echo "Generating APP_KEY..."
    php artisan key:generate --show > /tmp/appkey.txt
    APP_KEY=$(cat /tmp/appkey.txt)
    rm /tmp/appkey.txt
fi
echo "APP_KEY=$APP_KEY" >> .env

# Set APP_URL
echo "APP_URL=${APP_URL:-http://localhost}" >> .env

# Database - Critical Section
# Only default to pgsql if we have a host, otherwise stay flexible or default to mysql
if [ -z "$DB_CONNECTION" ]; then
    if [ -n "$DB_HOST" ]; then
        export DB_CONNECTION='pgsql'
    else
        export DB_CONNECTION='mysql'
    fi
fi

# Warn if pgsql is selected but no host is provided (will likely fail with 127.0.0.1)
if [ "$DB_CONNECTION" = "pgsql" ] && [ -z "$DB_HOST" ]; then
    echo "WARNING: DB_CONNECTION is set to pgsql but DB_HOST is missing. Connection may fail."
fi

# Write database configuration
echo "DB_CONNECTION=$DB_CONNECTION" >> .env
[ -n "$DB_HOST" ] && echo "DB_HOST=$DB_HOST" >> .env
[ -n "$DB_PORT" ] && echo "DB_PORT=$DB_PORT" >> .env
[ -n "$DB_DATABASE" ] && echo "DB_DATABASE=$DB_DATABASE" >> .env
[ -n "$DB_USERNAME" ] && echo "DB_USERNAME=$DB_USERNAME" >> .env
[ -n "$DB_PASSWORD" ] && echo "DB_PASSWORD=$DB_PASSWORD" >> .env

# Add session and cache configuration
echo "SESSION_DRIVER=file" >> .env
echo "CACHE_STORE=file" >> .env

echo "Done generating .env"
echo "=== Generated .env file ==="
cat .env
echo "==========================="

# CLEAR ALL CACHES - Critical to remove any cached MySQL config
echo "Clearing all Laravel caches..."
php artisan config:clear || true
php artisan cache:clear || true
php artisan route:clear || true
php artisan view:clear || true

# Remove any bootstrap cache files that might have old config
rm -f bootstrap/cache/config.php
rm -f bootstrap/cache/services.php
rm -f bootstrap/cache/packages.php

# Verify database configuration before migrations
echo "Verifying database configuration..."
php -r "require 'vendor/autoload.php'; \$app = require_once 'bootstrap/app.php'; \$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap(); echo 'DB Connection: ' . config('database.default') . PHP_EOL;"

# Run migrations WITHOUT cached config (so it reads fresh .env)
echo "Running migrations..."
php artisan migrate --force || echo "Migration failed, continuing..."

# NOW cache for production (after migrations succeed with correct DB)
echo "Caching configuration for production..."
php artisan config:cache
php artisan route:cache  
php artisan view:cache

echo "Starting server..."
exec php artisan serve --host=0.0.0.0 --port=10000
